[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[project]
name = "fourword"
version = "2.0.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.urls]
'GitHub' = 'https://github.com/nercone-labs/fourword/'

[project.scripts]
fourword = "fourword.cli:main"
